"""agregada tabla SecretoRastreador

Revision ID: cb3cd815523f
Revises: 62dfdd3ea46f
Create Date: 2026-08-25 14:41:48.812789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb3cd815523f'
down_revision: Union[str, Sequence[str], None] = '62dfdd3ea46f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secretorastreador',
    sa.Column('rastreador_serial', sa.String(length=50), nullable=False),
    sa.Column('secreto_hash', sa.String(length=60), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rastreador_serial'], ['rastreadoresadmin_rastreador.serial'], ),
    sa.PrimaryKeyConstraint('rastreador_serial')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secretorastreador')
    # ### end Alembic commands ###
