# Generated by Django 6.0.6 on 2026-06-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rastreador',
            fields=[
                ('serial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100)),
                ('imei', models.CharField(max_length=15, unique=True)),
                ('iccid', models.CharField(max_length=22, unique=True)),
                ('operador_red', models.CharField(max_length=20)),
            ],
        ),
    ]
