# Generated by Django 6.0.6 on 2026-06-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreadoresadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreador',
            name='numero_telefono',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
