# Generated by Django 6.0.6 on 2026-06-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreadoresadmin', '0002_rastreador_numero_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperadorRedMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='rastreador',
            name='operador_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador_red', to='rastreadoresadmin.operadorredmovil'),
        ),
    ]
