# Generated by Django 6.0.6 on 2026-06-27 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastreadoresadmin', '0003_operadorredmovil_alter_rastreador_operador_red'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rastreador',
            name='operador_red',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rastreadores', to='rastreadoresadmin.operadorredmovil'),
        ),
    ]
