# Generated by Django 6.0.6 on 2026-06-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rastreadoresadmin', '0004_alter_rastreador_operador_red'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operadorredmovil',
            options={'verbose_name': 'OperadorRedMovil', 'verbose_name_plural': 'OperadoresRedMovil'},
        ),
        migrations.RenameField(
            model_name='rastreador',
            old_name='numero_telefono',
            new_name='numero_sim',
        ),
    ]
