# Generated by Django 6.0.6 on 2026-06-29 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0005_alter_usuario_empresa'),
        ('rastreadoresadmin', '0005_alter_operadorredmovil_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rastreador',
            name='empresa_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rastreadores', to='loginuser.empresa'),
            preserve_default=False,
        ),
    ]
