# Generated by Django 6.0.6 on 2026-06-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rastreadoresadmin', '0006_rastreador_empresa_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rastreador',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
