# Generated by Django 6.0.6 on 2026-06-17 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paraderosadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradero',
            name='codigo',
            field=models.CharField(default='CM-P1', max_length=10),
            preserve_default=False,
        ),
    ]
