# Generated by Django 6.0.6 on 2026-08-03 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0005_alter_usuario_empresa'),
        ('paraderosadmin', '0002_paradero_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaParadero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paraderos', to='loginuser.empresa')),
            ],
        ),
    ]
