# Generated by Django 6.0.6 on 2026-08-03 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0005_alter_usuario_empresa'),
        ('paraderosadmin', '0003_empresaparadero'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresaparadero',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='empresaparadero',
            name='paradero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='paraderosadmin.paradero'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='empresaparadero',
            constraint=models.UniqueConstraint(fields=('empresa', 'paradero'), name='unique_paradero_empresa'),
        ),
        migrations.AddConstraint(
            model_name='empresaparadero',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='unique_codigo_paradero_empresa'),
        ),
    ]
