# Generated by Django 6.0.6 on 2026-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paraderosadmin', '0004_empresaparadero_codigo_empresaparadero_paradero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paradero',
            name='codigo',
        ),
        migrations.AlterField(
            model_name='empresaparadero',
            name='codigo',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
