# Generated by Django 6.0.6 on 2026-08-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paraderosadmin', '0005_remove_paradero_codigo_alter_empresaparadero_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paradero',
            name='radio',
            field=models.FloatField(default=500.0),
            preserve_default=False,
        ),
    ]
