"""
Django settings for RutaYa project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles';

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-77w(j43@3t$vcw@(rb3ouxy%8(jzqe#l$-#ba#ehq0n9t%nd-v'

# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "dashboard.tesis.rutaya.xyz"
]

env = environ.Env()
environ.Env.read_env(BASE_DIR.parent / ".env")

DEBUG = not env.bool("PRODUCTION", default=False)
                                                        
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'loginuser',
    'paraderosadmin',
    'busadmin',
    'rutasadmin',
    'rastreadoresadmin',
    'conductoresadmin',
    'rastreo'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'
]

ROOT_URLCONF = 'RutaYa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'RutaYa' /'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RutaYa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "RutaYa" / "static",
]

# MongoDB (histórico de posiciones de buses, alimentado por el bridge MQTT)
MONGO_URI = f"mongodb://{env("MONGODB_USER")}:{env("MONGODB_PASSWORD")}@{env("MONGODB_HOST")}:{env("MONGODB_PORT")}/{env("MONGODB_NAME")}?authSource=admin"
MONGO_DB = env("MONGODB_NAME")
MONGO_COLLECTION = env("MONGO_COLLECTION")

# Redis (estado actual de cada bus, alimentado por el bridge MQTT)
REDIS_HOST = env("REDIS_HOST")
REDIS_PORT = env("REDIS_PORT")
REDIS_DB = env("REDIS_DB")
REDIS_PASSWORD = env("REDIS_PASSWORD")

# Por defecto SecurityMiddleware envía "Referrer-Policy: same-origin", lo que hace
# que el navegador no mande Referer a los tiles de OpenStreetMap (dominio distinto)
# y su política de uso los rechace/limite por no poder identificar el origen.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"

AUTH_USER_MODEL = 'loginuser.Usuario'

LOGIN_URL="/"

AUTHENTICATION_BACKENDS = [
    'loginuser.backends.EmailBackend',
]
