# Generated by Django 6.0.6 on 2026-06-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.IntegerField()),
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('rastreador_mac', models.CharField(max_length=17, null=True, unique=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='busadmin.empresa')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='busadmin.ruta')),
            ],
        ),
    ]
