# Generated by Django 6.0.6 on 2026-06-06 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0001_initial'),
        ('loginuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='loginuser.empresa'),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
