# Generated by Django 6.0.6 on 2026-06-07 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0002_alter_bus_empresa_delete_empresa'),
        ('loginuser', '0005_alter_usuario_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='loginuser.empresa'),
            preserve_default=False,
        ),
    ]
