# Generated by Django 6.0.6 on 2026-06-09 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0003_ruta_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='busadmin.ruta'),
        ),
    ]
