# Generated by Django 6.0.6 on 2026-06-09 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0004_alter_bus_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ruta',
            name='empresa',
        ),
    ]
