# Generated by Django 6.0.6 on 2026-06-09 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0005_remove_ruta_empresa'),
        ('rutasadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='rutasadmin.ruta'),
        ),
        migrations.DeleteModel(
            name='Ruta',
        ),
    ]
