# Generated by Django 6.0.6 on 2026-06-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0006_alter_bus_ruta_delete_ruta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
    ]
