# Generated by Django 6.0.6 on 2026-06-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0007_alter_bus_options'),
        ('rutasadmin', '0005_alter_ruta_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='ruta',
        ),
        migrations.CreateModel(
            name='AsignacionRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ruta', to='busadmin.bus')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_ruta', to='rutasadmin.ruta')),
            ],
        ),
    ]
