# Generated by Django 6.0.6 on 2026-06-12 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0008_remove_bus_ruta_asignacionruta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='id',
            new_name='numero_bus',
        ),
    ]
