# Generated by Django 6.0.6 on 2026-06-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0009_rename_id_bus_numero_bus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionruta',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asignacionruta',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
