# Generated by Django 6.0.6 on 2026-06-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0010_alter_asignacionruta_fecha_fin_and_more'),
        ('loginuser', '0005_alter_usuario_empresa'),
        ('rutasadmin', '0005_alter_ruta_codigo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='asignacionruta',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('bus',), name='unique_bus_asignacion_activa'),
        ),
        migrations.AddConstraint(
            model_name='bus',
            constraint=models.UniqueConstraint(fields=('empresa', 'numero_bus'), name='unique_bus_numero_por_empresa'),
        ),
    ]
