# Generated by Django 6.0.6 on 2026-06-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0011_asignacionruta_unique_bus_asignacion_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='modelo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
