# Generated by Django 6.0.6 on 2026-06-14 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0012_bus_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='modelo',
            new_name='modelo_anio',
        ),
    ]
