# Generated by Django 6.0.6 on 2026-06-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0013_rename_modelo_bus_modelo_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='modelo_anio',
            field=models.IntegerField(),
        ),
    ]
