# Generated by Django 6.0.6 on 2026-06-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0014_alter_bus_modelo_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
