# Generated by Django 6.0.6 on 2026-06-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0015_bus_modelo'),
        ('rastreadoresadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='rastreador_mac',
        ),
        migrations.AddField(
            model_name='bus',
            name='rastreador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='rastreadoresadmin.rastreador'),
        ),
    ]
