# Generated by Django 6.0.6 on 2026-06-30 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0016_remove_bus_rastreador_mac_bus_rastreador'),
        ('rastreadoresadmin', '0007_rename_empresa_id_rastreador_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionRastreadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_inicio_fin', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rastreadores', to='busadmin.bus')),
                ('rastreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_rastreadores', to='rastreadoresadmin.rastreador')),
            ],
        ),
    ]
