# Generated by Django 6.0.6 on 2026-06-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0017_asignacionrastreadores'),
        ('rastreadoresadmin', '0007_rename_empresa_id_rastreador_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacionrastreadores',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rastreadores', to='busadmin.bus'),
        ),
        migrations.AlterField(
            model_name='asignacionrastreadores',
            name='rastreador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_rastreadores', to='rastreadoresadmin.rastreador'),
        ),
    ]
