# Generated by Django 6.0.6 on 2026-06-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0018_alter_asignacionrastreadores_bus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asignacionrastreadores',
            old_name='fecha_inicio_fin',
            new_name='fecha_fin',
        ),
    ]
