# Generated by Django 6.0.6 on 2026-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0019_rename_fecha_inicio_fin_asignacionrastreadores_fecha_fin'),
        ('rastreadoresadmin', '0007_rename_empresa_id_rastreador_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='rastreador',
        ),
        migrations.AddConstraint(
            model_name='asignacionrastreadores',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('bus',), name='unique_bus_asignacion_rastreador_activa'),
        ),
    ]
