# Generated by Django 6.0.6 on 2026-08-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busadmin', '0020_remove_bus_rastreador_fk_add_rastreador_constraint'),
        ('conductoresadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_conductor', to='busadmin.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_conductor', to='conductoresadmin.conductor')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('bus',), name='unique_bus_asignacion_conductor_activa'), models.UniqueConstraint(condition=models.Q(('fecha_fin__isnull', True)), fields=('conductor',), name='unique_conductor_asignacion_activa')],
            },
        ),
    ]
