# Generated by Django 6.0.6 on 2026-06-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='email',
        ),
    ]
