# Generated by Django 6.0.6 on 2026-06-07 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0002_remove_empresa_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
