# Generated by Django 6.0.6 on 2026-06-09 13:59

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutasadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='distancia_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ruta',
            name='recorrido',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
