# Generated by Django 6.0.6 on 2026-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutasadmin', '0002_ruta_distancia_km_ruta_recorrido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='nombre',
            new_name='punto_final',
        ),
        migrations.AddField(
            model_name='ruta',
            name='punto_inicio',
            field=models.CharField(default='Punto A', max_length=100),
            preserve_default=False,
        ),
    ]
