# Generated by Django 6.0.6 on 2026-06-10 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutasadmin', '0003_rename_nombre_ruta_punto_final_ruta_punto_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(default='CM-1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ruta',
            name='recorrido',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
