# Generated by Django 6.0.6 on 2026-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutasadmin', '0004_ruta_codigo_alter_ruta_recorrido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='codigo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
