# Generated by Django 6.0.6 on 2026-06-16 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paraderosadmin', '0001_initial'),
        ('rutasadmin', '0005_alter_ruta_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='punto_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='paraderosadmin.paradero'),
        ),
    ]
