# Generated by Django 6.0.6 on 2026-06-16 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paraderosadmin', '0001_initial'),
        ('rutasadmin', '0006_alter_ruta_punto_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='punto_final',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_final', to='paraderosadmin.paradero'),
        ),
        migrations.AlterField(
            model_name='ruta',
            name='punto_inicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas_inicio', to='paraderosadmin.paradero'),
        ),
    ]
