# Generated by Django 6.0.6 on 2026-08-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutasadmin', '0007_alter_ruta_punto_final_alter_ruta_punto_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='punto_inicio',
            new_name='paradero_inicio',
        ),
    ]
