# Generated by Django 6.0.6 on 2026-08-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutasadmin', '0008_rename_punto_inicio_ruta_paradero_inicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruta',
            old_name='punto_final',
            new_name='paradero_final',
        ),
    ]
