# Generated by Django 6.0.6 on 2026-08-07 11:55

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutasadmin', '0009_rename_punto_final_ruta_paradero_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='recorrido',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326),
        ),
    ]
