# Generated by Django 6.1 on 2026-08-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutasadmin', '0010_alter_ruta_recorrido'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(choices=[(0, 'LUN'), (1, 'MAR'), (2, 'MIE'), (3, 'JUE'), (4, 'VIE'), (5, 'SAB'), (6, 'DOM')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='rutasadmin.ruta')),
            ],
            options={
                'ordering': ['dia'],
                'constraints': [models.UniqueConstraint(fields=('ruta', 'dia'), name='unique_dia_por_ruta')],
            },
        ),
    ]
